# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

    -   package-ecosystem: "github-actions"
        directory: "/"
        target-branch: develop
        schedule:
            interval: "weekly"
        commit-message:
            prefix: "Action"
        labels:
            - "dependencies"

    -   package-ecosystem: "composer"
        directory: "/"
        target-branch: develop
        schedule:
            interval: "weekly"
        commit-message:
            prefix: "Composer"
        labels:
            - "dependencies"
            - "composer"

    -   package-ecosystem: "npm"
        directory: "/"
        target-branch: develop
        schedule:
            interval: "weekly"
        commit-message:
            prefix: "NPM"
        labels:
            - "dependencies"
            - "npm"
