name: Tests

on:
  push:
    # Main & Stage don't need to re-run tests run on develop
    branches-ignore:
      - 'main'
      - 'stage'
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/pest.yml'
      - 'composer.lock'

jobs:
  pest:
    name: Run tests
    if: |
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
      php: '8.3'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          key: extensions-${{ hashFiles('composer.lock') }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: List Installed Dependencies
        run: composer show -D

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          npm install --no-audit
          npm run build

      - name: Run pest
        run: ./vendor/bin/pest --stop-on-failure --parallel --display-skipped --processes=10
