name: Tests

on:
  push:
    # Main & Stage don't need to re-run tests run on develop
    branches-ignore:
      - 'main'
      - 'stage'
    paths:
      - '**.php'
      - '**.blade.php'
      - 'resources/css/**'
      - 'resources/js/**'
      - 'resources/views/**'
      - 'phpunit.xml'
      - '.github/workflows/pest.yml'
      - 'composer.lock'
      - 'package-lock.json'
      - 'package.json'
      - 'vite.config.js'
  pull_request:
    paths:
      - '**.php'
      - '**.blade.php'
      - 'resources/css/**'
      - 'resources/js/**'
      - 'resources/views/**'
      - 'phpunit.xml'
      - '.github/workflows/pest.yml'
      - 'composer.lock'
      - 'package-lock.json'
      - 'package.json'
      - 'vite.config.js'
  workflow_dispatch:

jobs:
  pest:
    name: Run tests
    if: |
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
      php: '8.5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          key: extensions-${{ hashFiles('composer.lock') }}

      - name: Cache extensions
        uses: actions/cache@v6
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Cache composer dependencies
        uses: actions/cache@v6
        with:
          path: vendor
          key: composer-php-${{ env.php }}-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: List Installed Dependencies
        run: composer show -D

      - name: Install node dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          npm run build

      - name: Run pest
        run: ./vendor/bin/pest --stop-on-failure --parallel --display-skipped --processes=10
