name: Stage Deploy

concurrency:
  group: staging
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Authenticate with 1Password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Inject secrets into environment
        run: |
          APP_ENV=test op inject -i .env.template_test -o .env --force

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_deploy

      - name: Transfer .env to server
        run: |
          # Configure identity file
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_deploy

          # Prepare Remote Data Directory
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
          [ ! -d "/home/${{ secrets.REMOTE_USER }}/bin" ] && mkdir -p "/home/${{ secrets.REMOTE_USER }}/bin" || true;
          [ ! -d "${{ secrets.REMOTE_TARGET }}" ] && mkdir -p "${{ secrets.REMOTE_TARGET }}" || true;
          [ ! -d "${{ secrets.REMOTE_TARGET }}/storage" ] && mkdir -p "${{ secrets.REMOTE_TARGET }}/storage" || true;
          [ ! -d "${{ secrets.REMOTE_TARGET }}/public/doc-files" ] && mkdir -p "${{ secrets.REMOTE_TARGET }}/public/doc-files" || true;
          [ ! -f "${{ secrets.REMOTE_TARGET }}/sitemap.xml" ] && touch "${{ secrets.REMOTE_TARGET }}/sitemap.xml" || true;
          [ ! -f "${{ secrets.REMOTE_TARGET }}/sitemap_pages.xml" ] && touch "${{ secrets.REMOTE_TARGET }}/sitemap_pages.xml" || true;
          [ ! -f "${{ secrets.REMOTE_TARGET }}/sitemap_docs.xml" ] && touch "${{ secrets.REMOTE_TARGET }}/sitemap_docs.xml" || true;
          '

          # Transfer file
          rsync -ap \
          .env \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}/.env

          # Send deploy script to server
          rsync -ap \
          bin/dep.sh \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/bin/dep.sh

      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.FORGE_TRIGGER_URL }}

