name: Stage Deploy

concurrency:
  group: staging
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Authenticate with 1Password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Inject secrets into environment
        run: |
          APP_ENV=test op inject -i .env.template_test -o .env.test

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Transfer .env to server
        run: |
          scp .env.test ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/testing/.env.test

          # Set proper permissions
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "chown ${{ secrets.REMOTE_USER }}:${{ secrets.REMOTE_USER }} /home/${{ secrets.REMOTE_USER }}/testing/env.test && chmod 600 /home/${{ secrets.REMOTE_USER }}/testing/env.test"

#      - name: Deploy
#        uses: jbrooksuk/laravel-forge-action@v1.0.2
#        with:
#          trigger_url: ${{ secrets.FORGE_TRIGGER_URL }}

